.
.TH "ROT13" "1" "July 2025" "rot13 be15fb3" "User Commands"
.
.SH "NAME"
\fbrot13\fR \- Perform a Caesar Shift
.
.SH "SYNOPSIS"
\fBrot13\fR \fIWORD\.\.\.\fR
.
.SH "DESCRIPTION"
\fBrot13\fR will perform a Caesar Cipher or Caesar shift on the argument. The arguments are printed almost exactly as they are shown to the program. Quotes are ignored.
.
.SH "Examples:"
.
.IP
\fBrot13 Hello, world!\fR
.IP
Uryyb, jbeyq!
.
.IP
\fBrot13 Uryyb, jbeyq!\fR
.IP
Hello, world!
.
.IP
\fBrot13 "rot13"\fR
.IP
ebg13
.
.SH "BUGS"
Report bugs at: https://github\.com/clifflocked/rot13/issues
.
.SH "AUTHOR"
Segen Stoutamire
